# Generated by Django 5.1.5 on 2026-06-06 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('harga', models.IntegerField()),
                ('stok', models.IntegerField()),
                ('halal', models.BooleanField(default=True)),
            ],
        ),
    ]
